#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Run `ttl2jsonxus -h` for help
#


from __future__ import print_function
from pyxus.utils.turtle_schema_transformer import transform_turtle_to_jsonld_schema as toNexus
import argparse
import json

#
# Local methods
#
def _parser():
     parser = argparse.ArgumentParser(description= \
                                      'Convert turtle format to nexus \
                                      compatible JSON-LD via pyxus.')
     parser.add_argument('--ttl', type=str, \
                         dest="ttl", \
                         help='Full path to input \
                               turtle file', \
                         nargs=1)
     parser.add_argument('--json', type=str, \
                         dest="json", \
                         help='Full path to output  \
                               nexus json file', \
                         nargs=1)
     return(parser)

parser = _parser()

def _args():
    return(parser.parse_args())

def _read_ttl(ttl_file):
    """
    Get turtle string
    """
    with open(ttl_file, "r") as f:
         ttl_schema  = f.read()
    return(ttl_schema)

def _to_json():
    """
    JSON converted string and file name requested
    """
    args        = _args()
    ttl_file    = args.ttl[0]
    json_schema = toNexus(_read_ttl(ttl_file))
    return(json_schema)
      
def _write_json(json_schema):
     args        = _args()
     with open(args.json[0], 'w') as outfile:
         json.dump(json_schema, outfile, \
                   sort_keys = True, indent = 4, \
                   ensure_ascii = False)
#
# Generate JSON from Turtle
# 
_write_json(_to_json())



